### ISSUE TITLE
计算行数报错

### ISSUE THREAD

**Issue by liuclub** [zly394/CollapsedTextView#9]
E/CrashHandler( 1837): UncaughtException detected: java.lang.NullPointerException:
        Attempt to invoke virtual method 'int android.text.Layout.getLineCount()' on a null object reference

E/CrashHandler( 1837): 	at com.zly.widget.CollapsedTextView.formatCollapsedText(CollapsedTextView.java:312)

E/CrashHandler( 1837): 	at com.zly.widget.CollapsedTextView.access$200(CollapsedTextView.java:34)

E/CrashHandler( 1837): 	at com.zly.widget.CollapsedTextView$1.onGlobalLayout(CollapsedTextView.java:285)

E/CrashHandler( 1837): 	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)

E/CrashHandler( 1837): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1950)

E/CrashHandler( 1837): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1105)

E/CrashHandler( 1837): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6189)

E/CrashHandler( 1837): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:793)

E/CrashHandler( 1837): 	at android.view.Choreographer.doCallbacks(Choreographer.java:606)

E/CrashHandler( 1837): 	at android.view.Choreographer.doFrame(Choreographer.java:575)

E/CrashHandler( 1837): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:779)

E/CrashHandler( 1837): 	at android.os.Handler.handleCallback(Handler.java:739)

E/CrashHandler( 1837): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/CrashHandler( 1837): 	at android.os.Looper.loop(Looper.java:135)

E/CrashHandler( 1837): 	at android.app.ActivityThread.main(ActivityThread.java:5601)

E/CrashHandler( 1837): 	at java.lang.reflect.Method.invoke(Native Method)

E/CrashHandler( 1837): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/CrashHandler( 1837): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)

E/CrashHandler( 1837): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

I/crash_recorder( 1837): recordTbsCrash:

I/crash_recorder( 1837):  {java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineCount()' on a null object reference

I/crash_recorder( 1837): 	at com.zly.widget.CollapsedTextView.formatCollapsedText(CollapsedTextView.java:312)

I/crash_recorder( 1837): 	at com.zly.widget.CollapsedTextView.access$200(CollapsedTextView.java:34)

I/crash_recorder( 1837): 	at com.zly.widget.CollapsedTextView$1.onGlobalLayout(CollapsedTextView.java:285)

I/crash_recorder( 1837): 	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)

I/crash_recorder( 1837): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1950)

I/crash_recorder( 1837): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1105)

I/crash_recorder( 1837): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6189)

I/crash_recorder( 1837): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:793)

I/crash_recorder( 1837): 	at android.view.Choreographer.doCallbacks(Choreographer.java:606)

I/crash_recorder( 1837): 	at android.view.Choreographer.doFrame(Choreographer.java:575)

I/crash_recorder( 1837): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:779)

I/crash_recorder( 1837): 	at android.os.Handler.handleCallback(Handl

**Comment by liuclub** [comment]
`ViewTreeObserver vto = mytextview.getViewTreeObserver();
 vto.addOnGlobalLayoutListener(new OnGlobalLayoutListener() { 
@Override 
public void onGlobalLayout() {
 Layout layout = mytextview.getLayout(); 
}
 });`
